name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "Bachelor_Project_StefanLica"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "main"

[doc-gen4]
only = ["Bachelor_Project_StefanLica"]
