name = "Bachelor_Project_StefanLica"
version = "0.1.0"
keywords = ["math"]


[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "Bachelor_Project_StefanLica"

[[tool]]
name = "doc-gen"
package = "doc-gen4"
