name = "Bachelor_Project_StefanLica"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Bachelor_Project_StefanLica"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Bachelor_Project_StefanLica"
